### ISSUE TITLE
How to add google analytics to Universal React

### ISSUE THREAD

**Issue by mp1pro** [remarkablemark/tutorials#10]
Title: How to add Google analytics to Universal React

I am having a hard time figuring out how to add google analytics to the server side of react. I am working on this project https://github.com/mp1pro/rastahealth which is a product of your tutorials. However, I am not sure of the best way how to accomplish this.

**Comment by remarkablemark** [comment]
Based on your implementation, the logic seems correct.

You may have forgotten to require Google Analytics in this [file](https://github.com/mp1pro/rastahealth/blob/master/routes/routes.jsx). Just insert the following line at the top:
```js
var ReactGA = require('react-ga');
```

Also, because my YouTube videos don't go deeply into making the web application production-ready, I recommend that you check out some useful [information](https://github.com/remarkablemark/tutorials/issues/8) on how to do that.

Let me know if this helps!

**Comment by mp1pro** [comment]
Your the boss, that worked
Thanks a mil
